# Form implementation generated from reading ui file 'C:\Users\smeta\source\repos\Работа\computervision\DPE-3364\uuid_maker\openEjectedObject.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_open_ejected_object(object):
    def setupUi(self, Form_open_ejected_object):
        Form_open_ejected_object.setObjectName("Form_open_ejected_object")
        Form_open_ejected_object.resize(704, 504)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_open_ejected_object)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form_open_ejected_object)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 684, 453))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_main = QtWidgets.QVBoxLayout()
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.verticalLayout_3.addLayout(self.verticalLayout_main)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent=Form_open_ejected_object)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form_open_ejected_object)
        QtCore.QMetaObject.connectSlotsByName(Form_open_ejected_object)

    def retranslateUi(self, Form_open_ejected_object):
        _translate = QtCore.QCoreApplication.translate
        Form_open_ejected_object.setWindowTitle(_translate("Form_open_ejected_object", "Form"))
        self.pushButton.setText(_translate("Form_open_ejected_object", "Выйти"))
