# Form implementation generated from reading ui file 'C:\Users\smeta\source\repos\Работа\computervision\DPE-3364\uuid_maker\table_objects.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_table_objects(object):
    def setupUi(self, Form_table_objects):
        Form_table_objects.setObjectName("Form_table_objects")
        Form_table_objects.resize(590, 601)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form_table_objects)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=Form_table_objects)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_sorted_objects = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_sorted_objects.setGeometry(QtCore.QRect(0, 0, 570, 581))
        self.scrollAreaWidgetContents_sorted_objects.setObjectName("scrollAreaWidgetContents_sorted_objects")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_sorted_objects)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_sorted_objects)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(Form_table_objects)
        QtCore.QMetaObject.connectSlotsByName(Form_table_objects)

    def retranslateUi(self, Form_table_objects):
        _translate = QtCore.QCoreApplication.translate
        Form_table_objects.setWindowTitle(_translate("Form_table_objects", "Form"))
